name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create Minimal Site
        run: |
          mkdir -p _site
          echo '<!DOCTYPE html>
          <html>
          <head><title>Success</title></head>
          <body>
            <h1>GitHub Pages Works!</h1>
            <p>Deployed: $(date)</p>
          </body>
          </html>' > _site/index.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        
      - name: Deploy
        uses: actions/deploy-pages@v3
